//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xxqLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentInfo()
        {
            this.MessageBoard = new HashSet<MessageBoard>();
        }
    
        public string Id { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string TypeId { get; set; }
        public string ContentText { get; set; }
        public bool ContentPublic { get; set; }
        public Nullable<System.DateTime> ContentCreatDate { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public bool IsManuscript { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageBoard> MessageBoard { get; set; }
    }
}
