//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xxqLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentType()
        {
            this.ContentInfo = new HashSet<ContentInfo>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public bool IsEffective { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentInfo> ContentInfo { get; set; }
    }
}
