//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xxqLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public string LoginLogId { get; set; }
        public string LoginUserId { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string LoginIP { get; set; }
        public bool LoginIsEnter { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
