//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xxqLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperateLog
    {
        public string OperateLogId { get; set; }
        public string OperateUserId { get; set; }
        public System.DateTime OperateDate { get; set; }
        public string OperateName { get; set; }
        public string OperateContent { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
